config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  get 'search_result', to: 'walkcourse#search'

  resources :walkcourses do
    resources :spots, only: [:new, :create, :edit, :update, :destroy]
    collection do
      get 'search'
    end
  end

  resources :users, only: [:show, :create, :edit, :update] do
    member do
      get :likes
      get :subjects
    end
  end
  resources :favorites, only: [:index, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6, maximum: 16 }
  belongs_to :prefecture
  has_many :walkcourses, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :likes, through: :favorites, source: :like
  has_many :reverses_of_favorite, class_name: 'Favorite', foreign_key: 'like_id'
  has_many :subjects, through: :reverses_of_favorite, source: :user

  def like(like_walkcourse)
    favorites.find_or_create_by(like_id: like_walkcourse.id)
  end

  def unlike(like_walkcourse)
    favorite = favorites.find_by(like_id: like_walkcourse.id)
    favorite&.destroy
  end

  def liking?(like_walkcourse)
    likes.include?(like_walkcourse)
  end

  def feed_favorites
    Walkcourse.where(id: like_ids)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :edit, :likes]
  before_action :set_search

  def show
    @user = User.find(params[:id])
    @walkcourses = current_user.walkcourses.order(id: :desc).page(params[:page]).per(3)
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'ユーザー情報の更新に成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザー情報の更新に失敗しました。'
      render 'edit'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def likes
    @user = User.find(params[:id])
    @walkcourses = @user.feed_favorites.order(id: :desc).page(params[:page]).per(3)
    counts(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :prefecture_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="text-center">
  <h1>ユーザー情報の編集</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.text_field :name, class: 'form-control', placeholder: "名前" %>
      </div>

      <div class="form-group">
        <%= f.email_field :email, class: 'form-control', placeholder: "メールアドレス" %>
      </div>

      <div class="form-group">
        <%= f.password_field :password, class: 'form-control', placeholder: "パスワード(6〜16文字)" %>
      </div>

      <div class="form-group">
        <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, placeholder: "都道府県を選択" %>
      </div>

      <%= f.submit '変更する', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/likes.html.erb
<div class="row users_showpage">
  <aside class="col-sm-4">
    <div class="card user_setting">
      <div class="card-header">
        <h3 class="card-title users_name"><%= @user.name %>さん</h3>
      </div>
      <div class="card-body">
        <ul class="users_info">
          <li>作成したコース<%= @count_walkcourses %>件</li>
          <li>お気に入り登録<%= @count_favorites %>件</li>
          <li class="cog_button"><i class="fas fa-cog"></i><%= link_to '設定', edit_user_path(@user) %></li>
        </ul>
      </div>
    </div>
  </aside>

  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">作成したコース</a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入りコース</a></li>
    </ul>
    <%= render 'walkcourses/walkcourses', walkcourses: @walkcourses, user: @user %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>メールアドレスで新規登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.text_field :name, class: 'form-control', placeholder: "名前" %>
      </div>

      <div class="form-group">
        <%= f.email_field :email, class: 'form-control', placeholder: "メールアドレス" %>
      </div>

      <div class="form-group">
        <%= f.password_field :password, class: 'form-control', placeholder: "パスワード(6〜16文字)" %>
      </div>

      <div class="form-group">
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "パスワード(確認)" %>
      </div>

      <div class="form-group">
        <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "選択してください" %>
      </div>

      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row users_showpage">
  <aside class="col-sm-4">
    <div class="card user_setting">
      <div class="card-header">
        <h3 class="card-title users_name"><%= @user.name %>さん</h3>
      </div>
      <div class="card-body">
        <ul class="users_info">
          <li>作成したコース<%= @count_walkcourses %>件</li>
          <li>お気に入り登録<%= @count_favorites %>件</li>
          <li class="cog_button"><i class="fas fa-cog"></i><%= link_to '設定', edit_user_path(@user) %></li>
        </ul>
      </div>
    </div>
  </aside>

  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">作成したコース</a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入りコース</a></li>
    </ul>
    <%= render 'walkcourses/walkcourses', walkcourses: @walkcourses, user: @user %>
  </div>
</div>