config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  get 'search_result', to: 'walkcourse#search'

  resources :walkcourses do
    resources :spots, only: [:new, :create, :edit, :update, :destroy]
    collection do
      get 'search'
    end
  end

  resources :users, only: [:show, :create, :edit, :update] do
    member do
      get :likes
      get :subjects
    end
  end
  resources :favorites, only: [:index, :create, :destroy]
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  before_action :set_search

  def index
    @created_walkcourses = Walkcourse.all.order(created_at: :asc).page(params[:page]).per(6)
    @favorite_walkcourses = Walkcourse.joins(:favorites).group('walkcourses.id', :like_id).order('count(favorites.user_id) desc').page(params[:page]).per(6)
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/toppages/index.html.erb
<div class="top-wrapper">
    <div class="service-phrase">
        <h1>
            <span>さんぽを通して</span>
            <br>
            <span>生活をたのしく、ゆたかに。</span>
            <br>
        </h1>
    </div>
</div>

<div class="main">
    <div class="sns-icon">
        <i class="fab fa-facebook-f footer-icon"></i>
        <i class="fab fa-twitter footer-icon"></i>
        <i class="fab fa-instagram footer-icon"></i>
    </div>

    <!--おすすめコースの表示-->
    <div class="recommend">
        <div class="recommend-title">
          <i class="fas fa-shoe-prints"></i>
          <h2>おすすめのコース</h2>
        </div>

        <div class="parent-table">
            <div class="row">
              <% @favorite_walkcourses.each do |favorite_walkcourse| %>
                <div class="col-4">
                  <div class="recommend-course">
                      <h3><%= link_to image_tag(favorite_walkcourse.coursepic.url, size: '325x200'), walkcourse_path(favorite_walkcourse) %></h3>
                      <p><%= favorite_walkcourse.title.truncate(20) %></p>
                      <p class="recommend-description"><%= favorite_walkcourse.description.truncate(40) %></p>
                  </div>
                </div>
              <% end %>
            </div>
        </div>
        <%= link_to "もっと見る", favorites_path, class: 'btn btn-default btn-block btn-show' %>
    </div>

    <div class="newpost">
        <i class="fas fa-bell"></i>
        <h2>新着コース</h2>
        <div class="parent-table">
          <div class="row">
            <% @created_walkcourses.each do |created_walkcourse| %>
              <div class="col-4">
                <div class="recommend-course">
                    <h3><%= link_to image_tag(created_walkcourse.coursepic.url, size: '325x200'), walkcourse_path(created_walkcourse) %></h3>
                    <p><%= created_walkcourse.title.truncate(20) %></p>
                    <p class="recommend-description"><%= created_walkcourse.description.truncate(40) %></p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <%= link_to "もっと見る", walkcourses_path, class: 'btn btn-default btn-block btn-show' %>
    </div>
</div>