config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  get 'search_result', to: 'walkcourse#search'

  resources :walkcourses do
    resources :spots, only: [:new, :create, :edit, :update, :destroy]
    collection do
      get 'search'
    end
  end

  resources :users, only: [:show, :create, :edit, :update] do
    member do
      get :likes
      get :subjects
    end
  end
  resources :favorites, only: [:index, :create, :destroy]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="flash_message alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
    <%= link_to image_tag('/assets/toppage_logo.png'), '/' %>
    <div class="header-right">
        <ul class="header-right-up">
            <% if logged_in? %>
                <li class="btn btn-default btn-block post_course"><%= link_to 'コースを投稿', new_walkcourse_path %></li>
                <li class="btn btn-default btn-block mypage"><%= link_to 'マイページ', user_path(current_user) %></li>
                <li class="btn btn-default btn-block logout"><%= link_to 'ログアウト', logout_path, method: :delete  %></li>
            <% else %>
                <li class="btn btn-default btn-block signup"><%= link_to '新規登録', signup_path %></li>
                <li class="btn btn-default btn-block login"><%= link_to 'ログイン', login_path %></li>
            <% end %>
        </ul>

        <div class="header-right-down">
          <% if @search %>
            <%= search_form_for @search, url: search_walkcourses_path do |f| %>
              <%= f.search_field :start_station_or_goal_station_or_title_or_description_or_spots_name_or_spots_address_or_spots_description_cont,class: "search_form", placeholder: "検索ワードを入力してください", size: "34x10" %>
              <%= button_tag type: 'submit', style: 'border-style: none;' do %>
                <i class="fas fa-search"></i>
              <% end %>
            <% end %>
          <% end %>
        </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>散歩道　街ブラ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- <link rel="stylesheet" href="stylesheet.css"> -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    <script src="//maps.google.com/maps/api/js?key=<%= ENV['GMAP_API_KEY'] %>"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

  </head>

  <body>
    <div class="wrapper">
      <%= render 'layouts/navbar' %>
      <div class="container">
        <%= render 'layouts/flash_messages' %>
        <%= yield %>
      </div>

      <footer>
          <small>copyright © 2020 Sanpomiti All rights reserved</small>
      </footer>
    </div>
  </body>
</html>